ALTER TABLE businesses
  ADD COLUMN IF NOT EXISTS account_type TEXT NOT NULL DEFAULT 'business',
  ADD COLUMN IF NOT EXISTS verification_status TEXT NOT NULL DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS policy_violation_code TEXT NULL,
  ADD COLUMN IF NOT EXISTS policy_violation_text TEXT NULL,
  ADD COLUMN IF NOT EXISTS last_nudge_at TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS nudge_message TEXT NULL,
  ADD COLUMN IF NOT EXISTS suspended_at TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS disabled_at TIMESTAMP NULL;
