ALTER TABLE businesses
  ADD COLUMN IF NOT EXISTS token_version INTEGER NOT NULL DEFAULT 0;

ALTER TABLE customers
  ADD COLUMN IF NOT EXISTS token_version INTEGER NOT NULL DEFAULT 0;

ALTER TABLE admins
  ADD COLUMN IF NOT EXISTS token_version INTEGER NOT NULL DEFAULT 0;
