const COMMUNITY_IMPACT_BADGES = [
  { slug: 'returning-citizen-employer', category: 'Employment & Economic Empowerment Badges', name: 'Returning Citizen Employer', description: 'Actively hires formerly incarcerated individuals.' },
  { slug: 'second-chance-workplace', category: 'Employment & Economic Empowerment Badges', name: 'Second-Chance Workplace', description: 'No blanket felony bans in hiring policy.' },
  { slug: 'youth-opportunity-partner', category: 'Employment & Economic Empowerment Badges', name: 'Youth Opportunity Partner', description: 'Employs or interns young adults (16–24), especially from underserved zip codes.' },
  { slug: 'foster-transition-employer', category: 'Employment & Economic Empowerment Badges', name: 'Foster Transition Employer', description: 'Hires individuals aging out of foster care.' },
  { slug: 'living-wage-employer', category: 'Employment & Economic Empowerment Badges', name: 'Living Wage Employer', description: 'Pays above local minimum wage benchmarks.' },
  { slug: 'local-hiring-champion', category: 'Employment & Economic Empowerment Badges', name: 'Local Hiring Champion', description: 'Majority of staff hired from surrounding community.' },
  { slug: 'workforce-training-sponsor', category: 'Employment & Economic Empowerment Badges', name: 'Workforce Training Sponsor', description: 'Funds certifications, apprenticeships, or skills training.' },
  { slug: 'human-trafficking-awareness-certified', category: 'Anti-Exploitation & Safety Badges', name: 'Human Trafficking Awareness Certified', description: 'Staff trained to recognize and report trafficking.' },
  { slug: 'child-protection-advocate', category: 'Anti-Exploitation & Safety Badges', name: 'Child Protection Advocate', description: 'Supports programs fighting child exploitation.' },
  { slug: 'safe-space-business', category: 'Anti-Exploitation & Safety Badges', name: 'Safe Space Business', description: 'Publicly commits to being a safe reporting location.' },
  { slug: 'survivor-employment-partner', category: 'Anti-Exploitation & Safety Badges', name: 'Survivor Employment Partner', description: 'Employs survivors of trafficking or abuse.' },
  { slug: 'minority-owned-verified', category: 'Financial & Ownership Equity Badges', name: 'Minority-Owned Verified', description: 'Certified minority-owned business.' },
  { slug: 'women-owned-verified', category: 'Financial & Ownership Equity Badges', name: 'Women-Owned Verified', description: 'Certified women-owned business.' },
  { slug: 'community-owned-business', category: 'Financial & Ownership Equity Badges', name: 'Community-Owned Business', description: 'Co-op model or employee ownership structure.' },
  { slug: 'profit-reinvestment-commitment', category: 'Financial & Ownership Equity Badges', name: 'Profit Reinvestment Commitment', description: 'Reinvests % of profits into local community.' },
  { slug: 'micro-entrepreneur-supporter', category: 'Financial & Ownership Equity Badges', name: 'Micro-Entrepreneur Supporter', description: 'Supports local vendors, pop-ups, small suppliers.' },
  { slug: 'scholarship-sponsor', category: 'Education & Advancement Badges', name: 'Scholarship Sponsor', description: 'Funds scholarships locally.' },
  { slug: 'ged-certification-supporter', category: 'Education & Advancement Badges', name: 'GED / Certification Supporter', description: 'Provides education stipends to employees.' },
  { slug: 'mentorship-provider', category: 'Education & Advancement Badges', name: 'Mentorship Provider', description: 'Runs structured mentorship programs.' },
  { slug: 'stem-advocate', category: 'Education & Advancement Badges', name: 'STEM Advocate', description: 'Supports tech, trades, or workforce skill programs.' },
  { slug: 'expungement-program-volunteer', category: 'Community Engagement Badges', name: 'Expungement Program Volunteer', description: 'Participates in record-clearing initiatives.' },
  { slug: 'community-volunteer-hours-verified', category: 'Community Engagement Badges', name: 'Community Volunteer Hours Verified', description: 'Documented volunteer contribution annually.' },
  { slug: 'local-nonprofit-partner', category: 'Community Engagement Badges', name: 'Local Nonprofit Partner', description: 'Ongoing relationship with local nonprofits.' },
  { slug: 'disaster-relief-contributor', category: 'Community Engagement Badges', name: 'Disaster Relief Contributor', description: 'Assists during community crises.' },
  { slug: 'ada-compliant-verified', category: 'Accessibility & Inclusion Badges', name: 'ADA-Compliant Verified', description: 'Physical and digital accessibility commitment.' },
  { slug: 'language-access-support', category: 'Accessibility & Inclusion Badges', name: 'Language Access Support', description: 'Multilingual services available.' },
  { slug: 'inclusive-hiring-policy', category: 'Accessibility & Inclusion Badges', name: 'Inclusive Hiring Policy', description: 'Explicit non-discrimination + inclusive practices.' },
  { slug: 'transportation-support-employer', category: 'Accessibility & Inclusion Badges', name: 'Transportation Support Employer', description: 'Helps employees with transportation access.' },
  { slug: 'digital-literacy-supporter', category: 'Digital & Economic Access Badges', name: 'Digital Literacy Supporter', description: 'Teaches digital skills in community.' },
  { slug: 'broadband-access-partner', category: 'Digital & Economic Access Badges', name: 'Broadband Access Partner', description: 'Helps reduce digital divide.' },
  { slug: 'small-business-mentor', category: 'Digital & Economic Access Badges', name: 'Small Business Mentor', description: 'Helps other small businesses grow.' },
  { slug: 'community-health-advocate', category: 'Additional Impact Badges', name: 'Community Health Advocate', description: 'Supports health access initiatives in underserved communities.' },
  { slug: 'food-security-supporter', category: 'Additional Impact Badges', name: 'Food Security Supporter', description: 'Contributes to food banks, meal programs, or hunger relief.' },
  { slug: 'affordable-housing-supporter', category: 'Additional Impact Badges', name: 'Affordable Housing Supporter', description: 'Invests in or supports affordable housing efforts.' },
  { slug: 'veteran-employment-supporter', category: 'Additional Impact Badges', name: 'Veteran Employment Supporter', description: 'Hires or actively supports military veterans.' },
  { slug: 'environmental-justice-partner', category: 'Additional Impact Badges', name: 'Environmental Justice Partner', description: 'Engages in environmental initiatives benefiting underserved areas.' },
  { slug: 'fair-chance-contracting-partner', category: 'Additional Impact Badges', name: 'Fair Chance Contracting Partner', description: 'Contracts with businesses owned by returning citizens.' },
  { slug: 'apprenticeship-program-provider', category: 'Additional Impact Badges', name: 'Apprenticeship Program Provider', description: 'Offers structured apprenticeship pathways.' },
  { slug: 'community-investment-champion', category: 'Additional Impact Badges', name: 'Community Investment Champion', description: 'Demonstrates sustained financial investment into local community development.' }
];

module.exports = { COMMUNITY_IMPACT_BADGES };
